//  REDUX ACTION TYPES

//  FETCHING-SORTING

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const SORT_BY = "SORT_BY"

//  SHOPPING CART

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CHANGE_QUANTITY = "CHANGE_QUANTITY"

//  WISHLIST

export const ADD_TO_WİSHLİST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WİSHLİST = "REMOVE_FROM_WISHLIST"
export const CLEAR_WISHLIST = "CLEAR_WISHLIST"

//  DISPLAY

export const DISPLAY_HELP_PAGE = "DISPLAY_HELP_PAGE"
export const DISPLAY_HELP_PORTAL = "DISPLAY_HELP_PORTAL"
export const DISPLAY_SEARCH_PAGE = "DISPLAY_SEARCH_PAGE"
export const DISPLAY_LAYOUT = "DISPLAY_LAYOUT"
export const DISPLAY_DIALOG = "DISPLAY_DIALOG"
export const CLOSE_DIALOG = "CLOSE_DIALOG"

//  NETLIFY-IDENTITY

export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"

//  SEARCH PRODUCTS

export const SEARCH_FOR_PRODUCTS = "SEARCH_FOR_PRODUCTS"
export const CLEAR_SEARCH_INPUT = "CLEAR_SEARCH_INPUT"

//  NEWSLETTER LIST

export const ADD_TO_LIST = "ADD_TO_LIST"

//  MESSAGES

export const SEND_MESSAGE = "SEND_MESSAGE"

//  SNACKBAR

export const SET_SNACKBAR = "SET_SNACKBAR"