// REDUX ACTION TYPES

//  COUNTER

// export const BASKET_INCREMENT = "BASKET_INCREMENT"
// export const BASKET_DECREMENT = "BASKET_DECREMENT"
// export const WISHLIST_INCREMENT = "WISHLIST_INCREMENT"
// export const WISHLIST_DECREMENT = "WISHLIST_DECREMENT"


//  ADDING-REMOVING

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADD_TO_WİSHLİST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WİSHLİST = "REMOVE_FROM_WISHLIST"


//   SORTING PRODUCTS

export const SORT_BY = "SORT_BY"

//  FETCHING

// export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
// export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
// export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"

//  DISPLAY

export const DISPLAY_HELP_PAGE = "DISPLAY_HELP_PAGE"
export const DISPLAY_SEARCH_PAGE = "DISPLAY_SEARCH_PAGE"
export const DISPLAY_LAYOUT = "DISPLAY_LAYOUT"
export const DISPLAY_DIALOG = "DISPLAY_DIALOG"
export const CLOSE_DIALOG = "CLOSE_DIALOG"